#!/bin/bash
rm ./download/bindings/soc/ti/sci-pm-domain.yaml
rm ./download/bindings/display/amlogic,meson-dw-hdmi.yaml
rm ./download/bindings/display/panel/innolux,ej030na.yaml
rm ./download/bindings/display/panel/mitsubishi,aa104xd12.yaml
rm ./download/bindings/display/panel/samsung,ld9040.yaml
rm ./download/bindings/display/panel/kingdisplay,kd035g6-54nt.yaml
rm ./download/bindings/display/panel/panel-lvds.yaml
rm ./download/bindings/display/panel/mitsubishi,aa121td01.yaml
rm ./download/bindings/display/panel/sgd,gktw70sdae4se.yaml
rm ./download/bindings/display/panel/sony,acx565akm.yaml
rm ./download/bindings/display/panel/innolux,ee101ia-01d.yaml
rm ./download/bindings/display/panel/ilitek,ili9322.yaml
rm ./download/bindings/display/panel/samsung,s6e63m0.yaml
rm ./download/bindings/display/panel/lgphilips,lb035q02.yaml
rm ./download/bindings/display/panel/tpo,td.yaml
rm ./download/bindings/display/panel/advantech,idk-1110wr.yaml
rm ./download/bindings/display/panel/sitronix,st7789v.yaml
rm ./download/bindings/display/panel/abt,y030xx067a.yaml
rm ./download/bindings/display/panel/panel-mipi-dbi-spi.yaml
rm ./download/bindings/net/brcm,mdio-mux-iproc.yaml
rm ./download/bindings/net/mdio-mux-gpio.yaml
rm ./download/bindings/net/mdio-mux-multiplexer.yaml
rm ./download/bindings/net/mdio-mux-mmioreg.yaml
rm ./download/bindings/net/dsa/dsa-port.yaml
rm ./download/bindings/input/mediatek,mt6779-keypad.yaml
rm ./download/bindings/input/google,cros-ec-keyb.yaml
rm ./download/bindings/input/imx-keypad.yaml
rm ./download/bindings/pci/brcm,iproc-pcie.yaml
rm ./download/bindings/pci/toshiba,visconti-pcie.yaml
rm ./download/bindings/pci/microchip,pcie-host.yaml
rm ./download/bindings/pci/apple,pcie.yaml
rm ./download/bindings/pci/brcm,stb-pcie.yaml
rm ./download/bindings/pci/sifive,fu740-pcie.yaml
rm ./download/bindings/pci/samsung,exynos-pcie.yaml
rm ./download/bindings/pci/hisilicon,kirin-pcie.yaml
rm ./download/bindings/pci/snps,dw-pcie-ep.yaml
rm ./download/bindings/pci/fsl,imx6q-pcie.yaml
rm ./download/bindings/pci/intel-gw-pcie.yaml
rm ./download/bindings/pci/socionext,uniphier-pcie-ep.yaml
rm ./download/bindings/auxdisplay/holtek,ht16k33.yaml
rm ./download/bindings/mfd/wlf,arizona.yaml
rm ./download/bindings/leds/register-bit-led.yaml
rm ./download/bindings/serial/8250_omap.yaml
rm ./download/bindings/mmc/arm,pl18x.yaml
rm ./download/bindings/interrupt-controller/ti,sci-inta.yaml
rm ./download/bindings/interrupt-controller/ti,sci-intr.yaml
rm ./download/bindings/watchdog/arm,sp805.yaml
rm ./download/bindings/gpio/gpio-virtio.yaml
rm ./download/bindings/remoteproc/ti,k3-dsp-rproc.yaml
rm ./download/bindings/thermal/samsung,exynos-thermal.yaml
rm ./download/bindings/i2c/i2c-mux-gpmux.yaml
rm ./download/bindings/i2c/i2c-virtio.yaml
rm ./download/bindings/i2c/i2c-mux-pca954x.yaml
rm ./download/bindings/mfd/cirrus,madera.yaml
rm ./download/bindings/sound/audio-graph-card.yaml
rm ./download/bindings/media/i2c/ovti,ov02a10.yaml
rm ./download/bindings/media/i2c/ovti,ov5640.yaml
rm ./download/bindings/memory-controllers/renesas,rpc-if.yaml
rm ./download/bindings/i3c/mipi-i3c-hci.yaml
rm ./download/bindings/dma/arm,pl330.yaml
rm ./download/bindings/dma/arm-pl08x.yaml
rm ./download/bindings/dma/ti/k3-bcdma.yaml
rm ./download/bindings/dma/ti/k3-pktdma.yaml
rm ./download/bindings/mtd/ti,gpmc-nand.yaml
rm ./download/bindings/mtd/ti,gpmc-onenand.yaml
rm ./download/bindings/mtd/jedec,spi-nor.yaml
rm ./download/bindings/mtd/partitions/nvmem-cells.yaml
rm ./download/bindings/pinctrl/qcom,sc8180x-pinctrl.yaml
rm ./download/bindings/pinctrl/qcom,mdm9607-pinctrl.yaml
rm ./download/bindings/pinctrl/qcom,sm8450-pinctrl.yaml
rm ./download/bindings/pinctrl/qcom,sm6125-pinctrl.yaml
rm ./download/bindings/pinctrl/qcom,sc8280xp-pinctrl.yaml
rm ./download/bindings/pinctrl/qcom,sm8350-pinctrl.yaml
rm ./download/bindings/pinctrl/qcom,sm6350-pinctrl.yaml
rm ./download/bindings/spi/spi-fsl-lpspi.yaml
rm ./download/bindings/spi/ingenic,spi.yaml
rm ./download/bindings/spi/mxs-spi.yaml
rm ./download/bindings/spi/mediatek,spi-slave-mt27xx.yaml
rm ./download/bindings/spi/mediatek,spi-mt65xx.yaml
rm ./download/bindings/spi/qcom,spi-qcom-qspi.yaml
rm ./download/bindings/spi/mediatek,spi-mtk-nor.yaml
rm ./download/bindings/spi/fsl-imx-cspi.yaml
rm ./download/bindings/spi/sprd,spi-adi.yaml
rm ./download/bindings/spi/spi-gpio.yaml
rm ./download/bindings/spi/spi-mux.yaml
rm ./download/bindings/arm/coresight-cti.yaml
